spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  #公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.entity
  mapperLocations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
