spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: utf-8
  freemarker:
    suffix: .html
    charset: UTF-8
    #设定静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**
mybatis:
  typeAliasesPackage: com.example.entity
  mapperLocations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql


